#include <stdio.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

int main()
{
    int fd[2];
    pid_t pid;
    char buffer[100];
    char data[] = "Data generated by the parent process";
    struct timespec start, end;
    double time_taken;

    if (pipe(fd) == -1)
    {
        perror("pipe failed");
        return 1;
    }

    clock_gettime(CLOCK_MONOTONIC, &start);

    pid = fork();

    if (pid < 0)
    {
        perror("fork failed");
        return 1;
    }

    if (pid == 0)
    {
        close(fd[1]);

        printf("Child Process - Consumer\n");
        printf("Child PID: %d\n", getpid());

        read(fd[0], buffer, sizeof(buffer));
        printf("Data consumed: %s\n", buffer);

        close(fd[0]);
        exit(0);
    }
    else
    {
        close(fd[0]);

        printf("Parent Process - Producer\n");
        printf("Parent PID: %d\n", getpid());
        printf("Data generated: %s\n", data);

        write(fd[1], data, strlen(data) + 1);

        close(fd[1]);

        wait(NULL);

        clock_gettime(CLOCK_MONOTONIC, &end);

        time_taken = (end.tv_sec - start.tv_sec) +
                     (end.tv_nsec - start.tv_nsec) / 1000000000.0;

        printf("Communication completed successfully.\n");
        printf("Communication time: %.6f seconds\n", time_taken);
    }

    return 0;
}
